esphome:
  name: $devicename
  on_boot:
    then:
      output.turn_on: switch_gpio_power

  on_shutdown:
    then:
      - output.turn_off: switch_gpio_power
      - lambda: |-
          gpio_hold_en(GPIO_NUM_25);
          gpio_deep_sleep_hold_en();

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home

ota:
  password: !secret ota_password

logger:
  level: verbose

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 30s
  run_duration: 30s

mqtt:
  broker: 192.168.100.5
  topic_prefix: esphome/${devicename}
  #  idf_send_async: true
  birth_message:
    topic: esphome/${devicename}/birth_status
    payload: "online"

  will_message:
    topic: esphome/${devicename}/will_status
    payload: "offline"

  on_message:
    - topic: esphome/${devicename}/ota_mode
      then:
        - deep_sleep.prevent: deep_sleep_1
        - lambda: |-
            ESP_LOGI("main", "Preventing deep sleep");

    - topic: esphome/${devicename}/sleep_mode
      then:
        - deep_sleep.enter: deep_sleep_1
        - lambda: |-
            ESP_LOGI("main", "Entering deep sleep");

output:
  - platform: gpio
    id: switch_gpio_power
    pin:
      number: 25
      mode:
        output: true
        pulldown: true

dallas:
  - pin: 27

network:
  enable_ipv6: false

sensor:
  - platform: dallas
    address: $oneWireAddress
    name: ${fullname} Temperature

  - platform: uptime
    name: ${fullname} Uptime

  - platform: wifi_signal
    name: ${fullname} Wifi Signal

  - platform: adc
    pin: 39
    name: ${fullname} Moisture
    update_interval: 10s
    attenuation: 11db
    unit_of_measurement: "%"
    icon: "mdi:water"
    accuracy_decimals: 0
    filters:
      - lambda: |-
          if (x > 2.1) {
            return 0;
          }
          if (x < 0.5) {
            return 100;
          }
          return (2.1 - x) / (2.1 - 0.5) * 100.0;
